### ISSUE TITLE
How do you get the difficulty score

### ISSUE THREAD

**Issue by JasmineYuer** [fvrtrp/wordsta#1]
Hi, 
Thank you so much for adding all those Toefl vocabulary in one place, but what's more importantly, the difficulty score! 
My questions are:
1. How do you get the difficulty score?
2. Why do you only include around 2000+ vocabularies? 

Thank you so much for sharing!

**Comment by surajk95** [comment]
Hi, 
Sorry for the late late reply

1. Have updated with difficulty scores, frequency, etc. for the lists (https://github.com/surajk95/wordsta/tree/master/app/lists)
2. Have added more lists
3. Have added examples of usage for available words
4. And finally, a brand new webpage for using the app (https://wordstaxyz.vercel.app/)
